### PR TITLE
Remove skip.record.on.skippable.exception config

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by lindong28** [comment]
Ping @smccauliff @becketqin for review.

**Comment by lindong28** [comment]
This patch removes the skip.record.on.skippable.exception for producer and consumer. User can choose to throw SkippableException in their custom serializer/de-serializer if they want the serliazation exception to be skipped.

**Comment by smccauliff** [comment]
Can you add a unit test on the consumer side?

**Comment by lindong28** [comment]
@smccauliff There are already tests for both producer and consumer that tests the behavior when SkippableException is thrown.

**Comment by smccauliff** [comment]
I see one that throws SerializationException but not SkippableException

**Comment by lindong28** [comment]
@smccauliff Could you check line 305 in ConsumerRecordsProcessorTest.java and line 106 in LiKafkaProducerIntegrationTest.java?

**Comment by smccauliff** [comment]
My bad.  I missed ConsumerRecordsProcessor.

**Comment by smccauliff** [comment]
LGMT

**Comment by lindong28** [comment]
@smccauliff Thanks!

**Pull request merged**
